[build]
builder = "static"
outputPath = "build"

[deploy]
numInstances = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"

[[services]]
name = "resumescreener"
httpPort = 3000
staticPath = "build"